[workspace]
name = "cellpose-trackastra"
description = "Python environments for the batch cellpose and trackastra projects"
authors = ["Vladimír Ulman <vladimir.ulman@vsb.cz>"]
repository = "https://github.com/xulman/TBA"

license = "BSD-2-Clause"
license-file = "LICENSE"
readme = "README.md"

platforms = ["linux-64", "win-64"]
channels = ["conda-forge", "pytorch"]
version = "0.0.1"

[environments]
cpu-v3 = ["cpu","v3"]
gpu-v3 = ["gpu","v3"]
cpu-v4 = ["cpu","v4"]
default = ["gpu","v4"]

[feature.cpu.system-requirements]
# empty

[feature.gpu.system-requirements]
cuda = "12.6"

[feature.cpu.dependencies]
pytorch = "2.6.*"

[feature.gpu.dependencies]
cuda-version = "==12.6"
pytorch-gpu = "2.6.*"

[feature.v3.dependencies]
cellpose = "<4.0.0"

[feature.v4.dependencies]
cellpose = ">=4.0.0"

[dependencies]
torchvision = ">=0.21.0,<0.22"
scikit-image = ">=0.24.0,<0.25"
scikit-learn = ">=1.5.2,<2"
tifffile = ">=2024.6.18,<2025"
imagecodecs = ">=2024.9.22,<2025"
tqdm = ">=4.67.1,<5"
