[workspace]
authors = ["Vladimír Ulman <ulman@fi.muni.cz>"]
channels = ["conda-forge"]
name = "containers"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
easybuild = ">=3.9.3,<4"
