[workspace]
authors = ["Vladimír Ulman <ulman@fi.muni.cz>"]
channels = ["conda-forge"]
name = "containers"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
numpy = ">=2.3.3,<3"
tifffile = ">=2025.10.16,<2026"
