[workspace]
authors = ["Vladimír Ulman <ulman@fi.muni.cz>"]
channels = ["conda-forge"]
name = "containers"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
#easybuild = ">=3.9.3,<4"
#lmod = ">=8.7.25,<9"
python = ">3.6"
pip = ">=25.2,<26"
lmod = ">=8.7.25,<9"
libibverbs-devel-cos6-x86_64 = ">=1.1.8,<2"
