[workspace]
authors = ["Vladimir Ulman <ulman@fi.muni.cz>"]
channels = ["conda-forge"]
name = "container"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
numpy = ">=2.3.3,<3"
scikit-image = ">=0.25.2,<0.26"
