[workspace]
authors = ["Vladimir Ulman <ulman@fi.muni.cz>"]
channels = ["conda-forge"]
name = "container"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.0,<3.15"
click = ">=8.3.0,<9"
tifffile = ">=2025.10.16,<2026"
imagecodecs = ">=2025.8.2,<2026"
